name: Github Action Demo
on: push
jobs:
  Premier-Job:
    name: Premier-Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Premier Job"
      - run: echo "Fin"     
  Deuxieme-Job:
    name: Deuxieme-Job
    runs-on: ubuntu-latest
    needs: Premier-Job
    steps:
      - run: echo "Deuxieme Job"
      - run: echo "Fin"  
